//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class Achievement {
		const string DBName = "achievement";
		#region members
		private int m_id = 0;
		private int m_atlas = 0;
		private string m_config = String.Empty;
		private int m_dailyType = 0;
		private int m_day = 0;
		private string m_day_show = String.Empty;
		private string m_des = String.Empty;
		private string m_field = String.Empty;
		private string m_icon = String.Empty;
		private int m_looklevel = 0;
		private int m_moneyType = 0;
		private string m_name = String.Empty;
		private int m_numcount = 0;
		private int m_open = 0;
		private int m_relationType = 0;
		private int m_sort = 0;
		private int m_star = 0;
		private int m_type = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, Achievement> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, Achievement>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int atlas { get { return m_atlas; } }
		public string config { get { return m_config; } }
		public int dailyType { get { return m_dailyType; } }
		public int day { get { return m_day; } }
		public string day_show { get { return m_day_show; } }
		public string des { get { return m_des; } }
		public string field { get { return m_field; } }
		public string icon { get { return m_icon; } }
		public int looklevel { get { return m_looklevel; } }
		public int moneyType { get { return m_moneyType; } }
		public string name { get { return m_name; } }
		public int numcount { get { return m_numcount; } }
		public int open { get { return m_open; } }
		public int relationType { get { return m_relationType; } }
		public int sort { get { return m_sort; } }
		public int star { get { return m_star; } }
		public int type { get { return m_type; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static Achievement __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static Achievement() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( Achievement ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, Achievement> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static Achievement ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new Achievement();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_atlas = __mask[ 1 ] ? q.GetInt( DBCache.FID_atlas, 5 ) : __default.m_atlas;
				temp.m_config = __mask[ 2 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_config, 6 ) : __default.m_config;
				temp.m_dailyType = __mask[ 3 ] ? q.GetInt( DBCache.FID_dailyType, 9 ) : __default.m_dailyType;
				temp.m_day = __mask[ 4 ] ? q.GetInt( DBCache.FID_day, 3 ) : __default.m_day;
				temp.m_day_show = __mask[ 5 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_day_show, 8 ) : __default.m_day_show;
				temp.m_des = __mask[ 6 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_des, 3 ) : __default.m_des;
				temp.m_field = __mask[ 7 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_field, 5 ) : __default.m_field;
				temp.m_icon = __mask[ 8 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_icon, 4 ) : __default.m_icon;
				temp.m_looklevel = __mask[ 9 ] ? q.GetInt( DBCache.FID_looklevel, 9 ) : __default.m_looklevel;
				temp.m_moneyType = __mask[ 10 ] ? q.GetInt( DBCache.FID_moneyType, 9 ) : __default.m_moneyType;
				temp.m_name = __mask[ 11 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_name, 4 ) : __default.m_name;
				temp.m_numcount = __mask[ 12 ] ? q.GetInt( DBCache.FID_numcount, 8 ) : __default.m_numcount;
				temp.m_open = __mask[ 13 ] ? q.GetInt( DBCache.FID_open, 4 ) : __default.m_open;
				temp.m_relationType = __mask[ 16 ] ? q.GetInt( DBCache.FID_relationType, 12 ) : __default.m_relationType;
				temp.m_sort = __mask[ 20 ] ? q.GetInt( DBCache.FID_sort, 4 ) : __default.m_sort;
				temp.m_star = __mask[ 21 ] ? q.GetInt( DBCache.FID_star, 4 ) : __default.m_star;
				temp.m_type = __mask[ 23 ] ? q.GetInt( DBCache.FID_type, 4 ) : __default.m_type;
				AchievementEx.IsValid_activePoint = __mask[ 0 ];
				AchievementEx.IsValid_reardMoney = __mask[ 14 ];
				AchievementEx.IsValid_Relation_UI = __mask[ 15 ];
				AchievementEx.IsValid_rewardItem = __mask[ 17 ];
				AchievementEx.IsValid_show_ui = __mask[ 18 ];
				AchievementEx.IsValid_showItem = __mask[ 19 ];
				AchievementEx.IsValid_targetList = __mask[ 22 ];
				if ( AchievementEx.onLoadComplexField_activePoint != null ) {
					AchievementEx.onLoadComplexField_activePoint( temp, q );
				}
				if ( AchievementEx.onLoadComplexField_reardMoney != null ) {
					AchievementEx.onLoadComplexField_reardMoney( temp, q );
				}
				if ( AchievementEx.onLoadComplexField_Relation_UI != null ) {
					AchievementEx.onLoadComplexField_Relation_UI( temp, q );
				}
				if ( AchievementEx.onLoadComplexField_rewardItem != null ) {
					AchievementEx.onLoadComplexField_rewardItem( temp, q );
				}
				if ( AchievementEx.onLoadComplexField_show_ui != null ) {
					AchievementEx.onLoadComplexField_show_ui( temp, q );
				}
				if ( AchievementEx.onLoadComplexField_showItem != null ) {
					AchievementEx.onLoadComplexField_showItem( temp, q );
				}
				if ( AchievementEx.onLoadComplexField_targetList != null ) {
					AchievementEx.onLoadComplexField_targetList( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static Achievement Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			Achievement ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x0b0c37e3;
		#endregion
	}

	public partial class AchievementEx {
		public delegate void LoadComplexField( Achievement data, LuaDatabase.Query q );
		internal static bool IsValid_activePoint = true;
		static LoadComplexField OnLoadComplexField_activePoint = null;
		public static LoadComplexField onLoadComplexField_activePoint {
			get {
				return OnLoadComplexField_activePoint;
			}
		}
		internal static bool IsValid_reardMoney = true;
		static LoadComplexField OnLoadComplexField_reardMoney = null;
		public static LoadComplexField onLoadComplexField_reardMoney {
			get {
				return OnLoadComplexField_reardMoney;
			}
		}
		internal static bool IsValid_Relation_UI = true;
		static LoadComplexField OnLoadComplexField_Relation_UI = null;
		public static LoadComplexField onLoadComplexField_Relation_UI {
			get {
				return OnLoadComplexField_Relation_UI;
			}
		}
		internal static bool IsValid_rewardItem = true;
		static LoadComplexField OnLoadComplexField_rewardItem = null;
		public static LoadComplexField onLoadComplexField_rewardItem {
			get {
				return OnLoadComplexField_rewardItem;
			}
		}
		internal static bool IsValid_show_ui = true;
		static LoadComplexField OnLoadComplexField_show_ui = null;
		public static LoadComplexField onLoadComplexField_show_ui {
			get {
				return OnLoadComplexField_show_ui;
			}
		}
		internal static bool IsValid_showItem = true;
		static LoadComplexField OnLoadComplexField_showItem = null;
		public static LoadComplexField onLoadComplexField_showItem {
			get {
				return OnLoadComplexField_showItem;
			}
		}
		internal static bool IsValid_targetList = true;
		static LoadComplexField OnLoadComplexField_targetList = null;
		public static LoadComplexField onLoadComplexField_targetList {
			get {
				return OnLoadComplexField_targetList;
			}
		}
	}
}
//EOF
