//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class Equipment {
		const string DBName = "equipment";
		#region members
		private int m_id = 0;
		private int m_atk_mag = 0;
		private int m_atk_phy = 0;
		private int m_Carrier = 0;
		private int m_def_mag = 0;
		private int m_def_phy = 0;
		private int m_EquipLevel = 0;
		private int m_hpmax = 0;
		private int m_Icon = 0;
		private int m_Icon_m = 0;
		private string m_Model = String.Empty;
		private string m_Model_m = String.Empty;
		private string m_Name = String.Empty;
		private int m_Qualitytype = 0;
		private int m_taskcollectId = 0;
		private int m_Type = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, Equipment> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, Equipment>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int atk_mag { get { return m_atk_mag; } }
		public int atk_phy { get { return m_atk_phy; } }
		public int Carrier { get { return m_Carrier; } }
		public int def_mag { get { return m_def_mag; } }
		public int def_phy { get { return m_def_phy; } }
		public int EquipLevel { get { return m_EquipLevel; } }
		public int hpmax { get { return m_hpmax; } }
		public int Icon { get { return m_Icon; } }
		public int Icon_m { get { return m_Icon_m; } }
		public string Model { get { return m_Model; } }
		public string Model_m { get { return m_Model_m; } }
		public string Name { get { return m_Name; } }
		public int Qualitytype { get { return m_Qualitytype; } }
		public int taskcollectId { get { return m_taskcollectId; } }
		public int Type { get { return m_Type; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static Equipment __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static Equipment() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( Equipment ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, Equipment> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static Equipment ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new Equipment();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_atk_mag = __mask[ 0 ] ? q.GetInt( DBCache.FID_atk_mag, 7 ) : __default.m_atk_mag;
				temp.m_atk_phy = __mask[ 1 ] ? q.GetInt( DBCache.FID_atk_phy, 7 ) : __default.m_atk_phy;
				temp.m_Carrier = __mask[ 2 ] ? q.GetInt( DBCache.FID_Carrier, 7 ) : __default.m_Carrier;
				temp.m_def_mag = __mask[ 3 ] ? q.GetInt( DBCache.FID_def_mag, 7 ) : __default.m_def_mag;
				temp.m_def_phy = __mask[ 4 ] ? q.GetInt( DBCache.FID_def_phy, 7 ) : __default.m_def_phy;
				temp.m_EquipLevel = __mask[ 5 ] ? q.GetInt( DBCache.FID_EquipLevel, 10 ) : __default.m_EquipLevel;
				temp.m_hpmax = __mask[ 6 ] ? q.GetInt( DBCache.FID_hpmax, 5 ) : __default.m_hpmax;
				temp.m_Icon = __mask[ 7 ] ? q.GetInt( DBCache.FID_Icon, 4 ) : __default.m_Icon;
				temp.m_Icon_m = __mask[ 8 ] ? q.GetInt( DBCache.FID_Icon_m, 6 ) : __default.m_Icon_m;
				temp.m_Model = __mask[ 9 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_Model, 5 ) : __default.m_Model;
				temp.m_Model_m = __mask[ 10 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_Model_m, 7 ) : __default.m_Model_m;
				temp.m_Name = __mask[ 11 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_Name, 4 ) : __default.m_Name;
				temp.m_Qualitytype = __mask[ 12 ] ? q.GetInt( DBCache.FID_Qualitytype, 11 ) : __default.m_Qualitytype;
				temp.m_taskcollectId = __mask[ 13 ] ? q.GetInt( DBCache.FID_taskcollectId, 13 ) : __default.m_taskcollectId;
				temp.m_Type = __mask[ 14 ] ? q.GetInt( DBCache.FID_Type, 4 ) : __default.m_Type;
				EquipmentEx.IsValid_UniqueAddprop = __mask[ 15 ];
				if ( EquipmentEx.onLoadComplexField_UniqueAddprop != null ) {
					EquipmentEx.onLoadComplexField_UniqueAddprop( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static Equipment Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			Equipment ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x1b4e17b4;
		#endregion
	}

	public partial class EquipmentEx {
		public delegate void LoadComplexField( Equipment data, LuaDatabase.Query q );
		internal static bool IsValid_UniqueAddprop = true;
		static LoadComplexField OnLoadComplexField_UniqueAddprop = null;
		public static LoadComplexField onLoadComplexField_UniqueAddprop {
			get {
				return OnLoadComplexField_UniqueAddprop;
			}
		}
	}
}
//EOF
