//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class Equip_Star_Collect {
		const string DBName = "equip_star_collect";
		#region members
		private int m_id = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, Equip_Star_Collect> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, Equip_Star_Collect>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static Equip_Star_Collect __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static Equip_Star_Collect() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( Equip_Star_Collect ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, Equip_Star_Collect> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static Equip_Star_Collect ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new Equip_Star_Collect();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				Equip_Star_CollectEx.IsValid_attribute_1 = __mask[ 0 ];
				Equip_Star_CollectEx.IsValid_attribute_2 = __mask[ 1 ];
				Equip_Star_CollectEx.IsValid_attribute_3 = __mask[ 2 ];
				Equip_Star_CollectEx.IsValid_attribute_4 = __mask[ 3 ];
				Equip_Star_CollectEx.IsValid_attribute_5 = __mask[ 4 ];
				if ( Equip_Star_CollectEx.onLoadComplexField_attribute_1 != null ) {
					Equip_Star_CollectEx.onLoadComplexField_attribute_1( temp, q );
				}
				if ( Equip_Star_CollectEx.onLoadComplexField_attribute_2 != null ) {
					Equip_Star_CollectEx.onLoadComplexField_attribute_2( temp, q );
				}
				if ( Equip_Star_CollectEx.onLoadComplexField_attribute_3 != null ) {
					Equip_Star_CollectEx.onLoadComplexField_attribute_3( temp, q );
				}
				if ( Equip_Star_CollectEx.onLoadComplexField_attribute_4 != null ) {
					Equip_Star_CollectEx.onLoadComplexField_attribute_4( temp, q );
				}
				if ( Equip_Star_CollectEx.onLoadComplexField_attribute_5 != null ) {
					Equip_Star_CollectEx.onLoadComplexField_attribute_5( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static Equip_Star_Collect Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			Equip_Star_Collect ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x5c5834da;
		#endregion
	}

	public partial class Equip_Star_CollectEx {
		public delegate void LoadComplexField( Equip_Star_Collect data, LuaDatabase.Query q );
		internal static bool IsValid_attribute_1 = true;
		static LoadComplexField OnLoadComplexField_attribute_1 = null;
		public static LoadComplexField onLoadComplexField_attribute_1 {
			get {
				return OnLoadComplexField_attribute_1;
			}
		}
		internal static bool IsValid_attribute_2 = true;
		static LoadComplexField OnLoadComplexField_attribute_2 = null;
		public static LoadComplexField onLoadComplexField_attribute_2 {
			get {
				return OnLoadComplexField_attribute_2;
			}
		}
		internal static bool IsValid_attribute_3 = true;
		static LoadComplexField OnLoadComplexField_attribute_3 = null;
		public static LoadComplexField onLoadComplexField_attribute_3 {
			get {
				return OnLoadComplexField_attribute_3;
			}
		}
		internal static bool IsValid_attribute_4 = true;
		static LoadComplexField OnLoadComplexField_attribute_4 = null;
		public static LoadComplexField onLoadComplexField_attribute_4 {
			get {
				return OnLoadComplexField_attribute_4;
			}
		}
		internal static bool IsValid_attribute_5 = true;
		static LoadComplexField OnLoadComplexField_attribute_5 = null;
		public static LoadComplexField onLoadComplexField_attribute_5 {
			get {
				return OnLoadComplexField_attribute_5;
			}
		}
	}
}
//EOF
