//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class FbProcess {
		const string DBName = "fb_process";
		#region members
		private int m_id = 0;
		private string m_cutscene = String.Empty;
		private int m_cutscenetype = 0;
		private int m_entermove_delay = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, FbProcess> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, FbProcess>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public string cutscene { get { return m_cutscene; } }
		public int cutscenetype { get { return m_cutscenetype; } }
		public int entermove_delay { get { return m_entermove_delay; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static FbProcess __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static FbProcess() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( FbProcess ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, FbProcess> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static FbProcess ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new FbProcess();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_cutscene = __mask[ 1 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_cutscene, 8 ) : __default.m_cutscene;
				temp.m_cutscenetype = __mask[ 2 ] ? q.GetInt( DBCache.FID_cutscenetype, 12 ) : __default.m_cutscenetype;
				temp.m_entermove_delay = __mask[ 5 ] ? q.GetInt( DBCache.FID_entermove_delay, 15 ) : __default.m_entermove_delay;
				FbProcessEx.IsValid_boss = __mask[ 0 ];
				FbProcessEx.IsValid_elite = __mask[ 3 ];
				FbProcessEx.IsValid_entermove = __mask[ 4 ];
				FbProcessEx.IsValid_fb_end = __mask[ 6 ];
				FbProcessEx.IsValid_monster = __mask[ 7 ];
				FbProcessEx.IsValid_show1 = __mask[ 8 ];
				if ( FbProcessEx.onLoadComplexField_boss != null ) {
					FbProcessEx.onLoadComplexField_boss( temp, q );
				}
				if ( FbProcessEx.onLoadComplexField_elite != null ) {
					FbProcessEx.onLoadComplexField_elite( temp, q );
				}
				if ( FbProcessEx.onLoadComplexField_entermove != null ) {
					FbProcessEx.onLoadComplexField_entermove( temp, q );
				}
				if ( FbProcessEx.onLoadComplexField_fb_end != null ) {
					FbProcessEx.onLoadComplexField_fb_end( temp, q );
				}
				if ( FbProcessEx.onLoadComplexField_monster != null ) {
					FbProcessEx.onLoadComplexField_monster( temp, q );
				}
				if ( FbProcessEx.onLoadComplexField_show1 != null ) {
					FbProcessEx.onLoadComplexField_show1( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static FbProcess Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			FbProcess ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x18a4a2e3;
		#endregion
	}

	public partial class FbProcessEx {
		public delegate void LoadComplexField( FbProcess data, LuaDatabase.Query q );
		internal static bool IsValid_boss = true;
		static LoadComplexField OnLoadComplexField_boss = null;
		public static LoadComplexField onLoadComplexField_boss {
			get {
				return OnLoadComplexField_boss;
			}
		}
		internal static bool IsValid_elite = true;
		static LoadComplexField OnLoadComplexField_elite = null;
		public static LoadComplexField onLoadComplexField_elite {
			get {
				return OnLoadComplexField_elite;
			}
		}
		internal static bool IsValid_entermove = true;
		static LoadComplexField OnLoadComplexField_entermove = null;
		public static LoadComplexField onLoadComplexField_entermove {
			get {
				return OnLoadComplexField_entermove;
			}
		}
		internal static bool IsValid_fb_end = true;
		static LoadComplexField OnLoadComplexField_fb_end = null;
		public static LoadComplexField onLoadComplexField_fb_end {
			get {
				return OnLoadComplexField_fb_end;
			}
		}
		internal static bool IsValid_monster = true;
		static LoadComplexField OnLoadComplexField_monster = null;
		public static LoadComplexField onLoadComplexField_monster {
			get {
				return OnLoadComplexField_monster;
			}
		}
		internal static bool IsValid_show1 = true;
		static LoadComplexField OnLoadComplexField_show1 = null;
		public static LoadComplexField onLoadComplexField_show1 {
			get {
				return OnLoadComplexField_show1;
			}
		}
	}
}
//EOF
