//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class Guild_Rank_Privilege {
		const string DBName = "guild_rank_privilege";
		#region members
		private int m_id = 0;
		private int m_auto_recruit = 0;
		private int m_change_name = 0;
		private int m_construction = 0;
		private int m_edit_announcement = 0;
		private int m_fire = 0;
		private int m_level = 0;
		private string m_name = String.Empty;
		private int m_rank_appointment = 0;
		private int m_recruit = 0;
		private int m_salaryBase = 0;
		private int m_salaryNum = 0;
		private int m_salaryType = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, Guild_Rank_Privilege> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, Guild_Rank_Privilege>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int auto_recruit { get { return m_auto_recruit; } }
		public int change_name { get { return m_change_name; } }
		public int construction { get { return m_construction; } }
		public int edit_announcement { get { return m_edit_announcement; } }
		public int fire { get { return m_fire; } }
		public int level { get { return m_level; } }
		public string name { get { return m_name; } }
		public int rank_appointment { get { return m_rank_appointment; } }
		public int recruit { get { return m_recruit; } }
		public int salaryBase { get { return m_salaryBase; } }
		public int salaryNum { get { return m_salaryNum; } }
		public int salaryType { get { return m_salaryType; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static Guild_Rank_Privilege __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static Guild_Rank_Privilege() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( Guild_Rank_Privilege ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, Guild_Rank_Privilege> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static Guild_Rank_Privilege ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new Guild_Rank_Privilege();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_auto_recruit = __mask[ 0 ] ? q.GetInt( DBCache.FID_auto_recruit, 12 ) : __default.m_auto_recruit;
				temp.m_change_name = __mask[ 1 ] ? q.GetInt( DBCache.FID_change_name, 11 ) : __default.m_change_name;
				temp.m_construction = __mask[ 2 ] ? q.GetInt( DBCache.FID_construction, 12 ) : __default.m_construction;
				temp.m_edit_announcement = __mask[ 3 ] ? q.GetInt( DBCache.FID_edit_announcement, 17 ) : __default.m_edit_announcement;
				temp.m_fire = __mask[ 4 ] ? q.GetInt( DBCache.FID_fire, 4 ) : __default.m_fire;
				temp.m_level = __mask[ 5 ] ? q.GetInt( DBCache.FID_level, 5 ) : __default.m_level;
				temp.m_name = __mask[ 6 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_name, 4 ) : __default.m_name;
				temp.m_rank_appointment = __mask[ 8 ] ? q.GetInt( DBCache.FID_rank_appointment, 16 ) : __default.m_rank_appointment;
				temp.m_recruit = __mask[ 9 ] ? q.GetInt( DBCache.FID_recruit, 7 ) : __default.m_recruit;
				temp.m_salaryBase = __mask[ 10 ] ? q.GetInt( DBCache.FID_salaryBase, 10 ) : __default.m_salaryBase;
				temp.m_salaryNum = __mask[ 11 ] ? q.GetInt( DBCache.FID_salaryNum, 9 ) : __default.m_salaryNum;
				temp.m_salaryType = __mask[ 12 ] ? q.GetInt( DBCache.FID_salaryType, 10 ) : __default.m_salaryType;
				Guild_Rank_PrivilegeEx.IsValid_open_events = __mask[ 7 ];
				if ( Guild_Rank_PrivilegeEx.onLoadComplexField_open_events != null ) {
					Guild_Rank_PrivilegeEx.onLoadComplexField_open_events( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static Guild_Rank_Privilege Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			Guild_Rank_Privilege ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x144b3602;
		#endregion
	}

	public partial class Guild_Rank_PrivilegeEx {
		public delegate void LoadComplexField( Guild_Rank_Privilege data, LuaDatabase.Query q );
		internal static bool IsValid_open_events = true;
		static LoadComplexField OnLoadComplexField_open_events = null;
		public static LoadComplexField onLoadComplexField_open_events {
			get {
				return OnLoadComplexField_open_events;
			}
		}
	}
}
//EOF
