//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class Guild_Donate {
		const string DBName = "guild_donate";
		#region members
		private int m_id = 0;
		private string m_des = String.Empty;
		private int m_giveItemId = 0;
		private int m_guid_expe = 0;
		private int m_guild_contri = 0;
		private int m_guild_paly = 0;
		private int m_guild_prot = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, Guild_Donate> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, Guild_Donate>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public string des { get { return m_des; } }
		public int giveItemId { get { return m_giveItemId; } }
		public int guid_expe { get { return m_guid_expe; } }
		public int guild_contri { get { return m_guild_contri; } }
		public int guild_paly { get { return m_guild_paly; } }
		public int guild_prot { get { return m_guild_prot; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static Guild_Donate __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static Guild_Donate() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( Guild_Donate ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, Guild_Donate> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static Guild_Donate ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new Guild_Donate();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_des = __mask[ 1 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_des, 3 ) : __default.m_des;
				temp.m_giveItemId = __mask[ 2 ] ? q.GetInt( DBCache.FID_giveItemId, 10 ) : __default.m_giveItemId;
				temp.m_guid_expe = __mask[ 3 ] ? q.GetInt( DBCache.FID_guid_expe, 9 ) : __default.m_guid_expe;
				temp.m_guild_contri = __mask[ 4 ] ? q.GetInt( DBCache.FID_guild_contri, 12 ) : __default.m_guild_contri;
				temp.m_guild_paly = __mask[ 6 ] ? q.GetInt( DBCache.FID_guild_paly, 10 ) : __default.m_guild_paly;
				temp.m_guild_prot = __mask[ 7 ] ? q.GetInt( DBCache.FID_guild_prot, 10 ) : __default.m_guild_prot;
				Guild_DonateEx.IsValid_consumption = __mask[ 0 ];
				Guild_DonateEx.IsValid_guild_ewards = __mask[ 5 ];
				Guild_DonateEx.IsValid_self_exp = __mask[ 8 ];
				if ( Guild_DonateEx.onLoadComplexField_consumption != null ) {
					Guild_DonateEx.onLoadComplexField_consumption( temp, q );
				}
				if ( Guild_DonateEx.onLoadComplexField_guild_ewards != null ) {
					Guild_DonateEx.onLoadComplexField_guild_ewards( temp, q );
				}
				if ( Guild_DonateEx.onLoadComplexField_self_exp != null ) {
					Guild_DonateEx.onLoadComplexField_self_exp( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static Guild_Donate Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			Guild_Donate ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x23757e56;
		#endregion
	}

	public partial class Guild_DonateEx {
		public delegate void LoadComplexField( Guild_Donate data, LuaDatabase.Query q );
		internal static bool IsValid_consumption = true;
		static LoadComplexField OnLoadComplexField_consumption = null;
		public static LoadComplexField onLoadComplexField_consumption {
			get {
				return OnLoadComplexField_consumption;
			}
		}
		internal static bool IsValid_guild_ewards = true;
		static LoadComplexField OnLoadComplexField_guild_ewards = null;
		public static LoadComplexField onLoadComplexField_guild_ewards {
			get {
				return OnLoadComplexField_guild_ewards;
			}
		}
		internal static bool IsValid_self_exp = true;
		static LoadComplexField OnLoadComplexField_self_exp = null;
		public static LoadComplexField onLoadComplexField_self_exp {
			get {
				return OnLoadComplexField_self_exp;
			}
		}
	}
}
//EOF
