//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class GuildXM {
		const string DBName = "guild";
		#region members
		private int m_id = 0;
		private int m_guild_exp = 0;
		private int m_leader_1 = 0;
		private int m_leader_2 = 0;
		private int m_leader_3 = 0;
		private int m_leader_4 = 0;
		private int m_leader_5 = 0;
		private int m_menber_number = 0;
		private int m_reward = 0;
		private int m_shop = 0;
		private int m_wonder = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, GuildXM> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, GuildXM>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int guild_exp { get { return m_guild_exp; } }
		public int leader_1 { get { return m_leader_1; } }
		public int leader_2 { get { return m_leader_2; } }
		public int leader_3 { get { return m_leader_3; } }
		public int leader_4 { get { return m_leader_4; } }
		public int leader_5 { get { return m_leader_5; } }
		public int menber_number { get { return m_menber_number; } }
		public int reward { get { return m_reward; } }
		public int shop { get { return m_shop; } }
		public int wonder { get { return m_wonder; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static GuildXM __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static GuildXM() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( GuildXM ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, GuildXM> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static GuildXM ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new GuildXM();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_guild_exp = __mask[ 1 ] ? q.GetInt( DBCache.FID_guild_exp, 9 ) : __default.m_guild_exp;
				temp.m_leader_1 = __mask[ 2 ] ? q.GetInt( DBCache.FID_leader_1, 8 ) : __default.m_leader_1;
				temp.m_leader_2 = __mask[ 3 ] ? q.GetInt( DBCache.FID_leader_2, 8 ) : __default.m_leader_2;
				temp.m_leader_3 = __mask[ 4 ] ? q.GetInt( DBCache.FID_leader_3, 8 ) : __default.m_leader_3;
				temp.m_leader_4 = __mask[ 5 ] ? q.GetInt( DBCache.FID_leader_4, 8 ) : __default.m_leader_4;
				temp.m_leader_5 = __mask[ 6 ] ? q.GetInt( DBCache.FID_leader_5, 8 ) : __default.m_leader_5;
				temp.m_menber_number = __mask[ 7 ] ? q.GetInt( DBCache.FID_menber_number, 13 ) : __default.m_menber_number;
				temp.m_reward = __mask[ 8 ] ? q.GetInt( DBCache.FID_reward, 6 ) : __default.m_reward;
				temp.m_shop = __mask[ 9 ] ? q.GetInt( DBCache.FID_shop, 4 ) : __default.m_shop;
				temp.m_wonder = __mask[ 10 ] ? q.GetInt( DBCache.FID_wonder, 6 ) : __default.m_wonder;
				GuildXMEx.IsValid_exp_fb = __mask[ 0 ];
				if ( GuildXMEx.onLoadComplexField_exp_fb != null ) {
					GuildXMEx.onLoadComplexField_exp_fb( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static GuildXM Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			GuildXM ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x50f9f400;
		#endregion
	}

	public partial class GuildXMEx {
		public delegate void LoadComplexField( GuildXM data, LuaDatabase.Query q );
		internal static bool IsValid_exp_fb = true;
		static LoadComplexField OnLoadComplexField_exp_fb = null;
		public static LoadComplexField onLoadComplexField_exp_fb {
			get {
				return OnLoadComplexField_exp_fb;
			}
		}
	}
}
//EOF
