//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class Head {
		const string DBName = "head";
		#region members
		private int m_id = 0;
		private int m_active_itemID = 0;
		private string m_Desc = String.Empty;
		private string m_head_name = String.Empty;
		private int m_head_type = 0;
		private int m_hide = 0;
		private string m_name = String.Empty;
		private int m_resID = 0;
		private int m_time = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, Head> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, Head>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int active_itemID { get { return m_active_itemID; } }
		public string Desc { get { return m_Desc; } }
		public string head_name { get { return m_head_name; } }
		public int head_type { get { return m_head_type; } }
		public int hide { get { return m_hide; } }
		public string name { get { return m_name; } }
		public int resID { get { return m_resID; } }
		public int time { get { return m_time; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static Head __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static Head() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( Head ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, Head> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static Head ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new Head();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_active_itemID = __mask[ 0 ] ? q.GetInt( DBCache.FID_active_itemID, 13 ) : __default.m_active_itemID;
				temp.m_Desc = __mask[ 2 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_Desc, 4 ) : __default.m_Desc;
				temp.m_head_name = __mask[ 3 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_head_name, 9 ) : __default.m_head_name;
				temp.m_head_type = __mask[ 4 ] ? q.GetInt( DBCache.FID_head_type, 9 ) : __default.m_head_type;
				temp.m_hide = __mask[ 5 ] ? q.GetInt( DBCache.FID_hide, 4 ) : __default.m_hide;
				temp.m_name = __mask[ 6 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_name, 4 ) : __default.m_name;
				temp.m_resID = __mask[ 7 ] ? q.GetInt( DBCache.FID_resID, 5 ) : __default.m_resID;
				temp.m_time = __mask[ 8 ] ? q.GetInt( DBCache.FID_time, 4 ) : __default.m_time;
				HeadEx.IsValid_attribute = __mask[ 1 ];
				if ( HeadEx.onLoadComplexField_attribute != null ) {
					HeadEx.onLoadComplexField_attribute( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static Head Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			Head ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x065abec6;
		#endregion
	}

	public partial class HeadEx {
		public delegate void LoadComplexField( Head data, LuaDatabase.Query q );
		internal static bool IsValid_attribute = true;
		static LoadComplexField OnLoadComplexField_attribute = null;
		public static LoadComplexField onLoadComplexField_attribute {
			get {
				return OnLoadComplexField_attribute;
			}
		}
	}
}
//EOF
