//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class ItemDiscount {
		const string DBName = "item_discount";
		#region members
		private int m_id = 0;
		private int m_discount = 0;
		private string m_model_name = String.Empty;
		private float m_model_zoom = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, ItemDiscount> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, ItemDiscount>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int discount { get { return m_discount; } }
		public string model_name { get { return m_model_name; } }
		public float model_zoom { get { return m_model_zoom; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static ItemDiscount __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static ItemDiscount() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( ItemDiscount ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, ItemDiscount> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static ItemDiscount ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new ItemDiscount();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_discount = __mask[ 0 ] ? q.GetInt( DBCache.FID_discount, 8 ) : __default.m_discount;
				temp.m_model_name = __mask[ 3 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_model_name, 10 ) : __default.m_model_name;
				temp.m_model_zoom = __mask[ 5 ] ? q.GetFloat( DBCache.FID_model_zoom, 10 ) : __default.m_model_zoom;
				ItemDiscountEx.IsValid_itemid = __mask[ 1 ];
				ItemDiscountEx.IsValid_model_hight = __mask[ 2 ];
				ItemDiscountEx.IsValid_model_s = __mask[ 4 ];
				ItemDiscountEx.IsValid_OriginalPrice = __mask[ 6 ];
				ItemDiscountEx.IsValid_PresentPrice = __mask[ 7 ];
				if ( ItemDiscountEx.onLoadComplexField_itemid != null ) {
					ItemDiscountEx.onLoadComplexField_itemid( temp, q );
				}
				if ( ItemDiscountEx.onLoadComplexField_model_hight != null ) {
					ItemDiscountEx.onLoadComplexField_model_hight( temp, q );
				}
				if ( ItemDiscountEx.onLoadComplexField_model_s != null ) {
					ItemDiscountEx.onLoadComplexField_model_s( temp, q );
				}
				if ( ItemDiscountEx.onLoadComplexField_OriginalPrice != null ) {
					ItemDiscountEx.onLoadComplexField_OriginalPrice( temp, q );
				}
				if ( ItemDiscountEx.onLoadComplexField_PresentPrice != null ) {
					ItemDiscountEx.onLoadComplexField_PresentPrice( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static ItemDiscount Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			ItemDiscount ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x3a04b117;
		#endregion
	}

	public partial class ItemDiscountEx {
		public delegate void LoadComplexField( ItemDiscount data, LuaDatabase.Query q );
		internal static bool IsValid_itemid = true;
		static LoadComplexField OnLoadComplexField_itemid = null;
		public static LoadComplexField onLoadComplexField_itemid {
			get {
				return OnLoadComplexField_itemid;
			}
		}
		internal static bool IsValid_model_hight = true;
		static LoadComplexField OnLoadComplexField_model_hight = null;
		public static LoadComplexField onLoadComplexField_model_hight {
			get {
				return OnLoadComplexField_model_hight;
			}
		}
		internal static bool IsValid_model_s = true;
		static LoadComplexField OnLoadComplexField_model_s = null;
		public static LoadComplexField onLoadComplexField_model_s {
			get {
				return OnLoadComplexField_model_s;
			}
		}
		internal static bool IsValid_OriginalPrice = true;
		static LoadComplexField OnLoadComplexField_OriginalPrice = null;
		public static LoadComplexField onLoadComplexField_OriginalPrice {
			get {
				return OnLoadComplexField_OriginalPrice;
			}
		}
		internal static bool IsValid_PresentPrice = true;
		static LoadComplexField OnLoadComplexField_PresentPrice = null;
		public static LoadComplexField onLoadComplexField_PresentPrice {
			get {
				return OnLoadComplexField_PresentPrice;
			}
		}
	}
}
//EOF
