//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class ItemMix {
		const string DBName = "item_mix";
		#region members
		private int m_id = 0;
		private int m_Carrier = 0;
		private int m_goldnum = 0;
		private int m_goldtype = 0;
		private int m_group_main = 0;
		private int m_item1 = 0;
		private int m_item1_num = 0;
		private int m_item2 = 0;
		private int m_item2_num = 0;
		private int m_item3 = 0;
		private int m_item3_num = 0;
		private int m_item4 = 0;
		private int m_item4_num = 0;
		private string m_item_str = String.Empty;
		private int m_num_perday = 0;
		private int m_succ_rate = 0;
		private int m_target_item = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, ItemMix> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, ItemMix>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int Carrier { get { return m_Carrier; } }
		public int goldnum { get { return m_goldnum; } }
		public int goldtype { get { return m_goldtype; } }
		public int group_main { get { return m_group_main; } }
		public int item1 { get { return m_item1; } }
		public int item1_num { get { return m_item1_num; } }
		public int item2 { get { return m_item2; } }
		public int item2_num { get { return m_item2_num; } }
		public int item3 { get { return m_item3; } }
		public int item3_num { get { return m_item3_num; } }
		public int item4 { get { return m_item4; } }
		public int item4_num { get { return m_item4_num; } }
		public string item_str { get { return m_item_str; } }
		public int num_perday { get { return m_num_perday; } }
		public int succ_rate { get { return m_succ_rate; } }
		public int target_item { get { return m_target_item; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static ItemMix __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static ItemMix() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( ItemMix ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, ItemMix> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static ItemMix ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new ItemMix();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_Carrier = __mask[ 0 ] ? q.GetInt( DBCache.FID_Carrier, 7 ) : __default.m_Carrier;
				temp.m_goldnum = __mask[ 1 ] ? q.GetInt( DBCache.FID_goldnum, 7 ) : __default.m_goldnum;
				temp.m_goldtype = __mask[ 2 ] ? q.GetInt( DBCache.FID_goldtype, 8 ) : __default.m_goldtype;
				temp.m_group_main = __mask[ 3 ] ? q.GetInt( DBCache.FID_group_main, 10 ) : __default.m_group_main;
				temp.m_item1 = __mask[ 4 ] ? q.GetInt( DBCache.FID_item1, 5 ) : __default.m_item1;
				temp.m_item1_num = __mask[ 5 ] ? q.GetInt( DBCache.FID_item1_num, 9 ) : __default.m_item1_num;
				temp.m_item2 = __mask[ 6 ] ? q.GetInt( DBCache.FID_item2, 5 ) : __default.m_item2;
				temp.m_item2_num = __mask[ 7 ] ? q.GetInt( DBCache.FID_item2_num, 9 ) : __default.m_item2_num;
				temp.m_item3 = __mask[ 8 ] ? q.GetInt( DBCache.FID_item3, 5 ) : __default.m_item3;
				temp.m_item3_num = __mask[ 9 ] ? q.GetInt( DBCache.FID_item3_num, 9 ) : __default.m_item3_num;
				temp.m_item4 = __mask[ 10 ] ? q.GetInt( DBCache.FID_item4, 5 ) : __default.m_item4;
				temp.m_item4_num = __mask[ 11 ] ? q.GetInt( DBCache.FID_item4_num, 9 ) : __default.m_item4_num;
				temp.m_item_str = __mask[ 12 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_item_str, 8 ) : __default.m_item_str;
				temp.m_num_perday = __mask[ 13 ] ? q.GetInt( DBCache.FID_num_perday, 10 ) : __default.m_num_perday;
				temp.m_succ_rate = __mask[ 14 ] ? q.GetInt( DBCache.FID_succ_rate, 9 ) : __default.m_succ_rate;
				temp.m_target_item = __mask[ 15 ] ? q.GetInt( DBCache.FID_target_item, 11 ) : __default.m_target_item;
				return temp;
			}
			return null;
		}

 		public static ItemMix Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			ItemMix ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x706814ff;
		#endregion
	}
}
//EOF
