//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class MainMenu {
		const string DBName = "mainMenu";
		#region members
		private int m_id = 0;
		private string m_cehuazijikan = String.Empty;
		private int m_effect = 0;
		private int m_effect2 = 0;
		private int m_icon = 0;
		private int m_is_reddot = 0;
		private string m_Name = String.Empty;
		private int m_openid = 0;
		private int m_Parameters = 0;
		private int m_severcontrol = 0;
		private int m_showpane = 0;
		private int m_sort = 0;
		private int m_special_open = 0;
		private int m_type = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, MainMenu> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, MainMenu>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public string cehuazijikan { get { return m_cehuazijikan; } }
		public int effect { get { return m_effect; } }
		public int effect2 { get { return m_effect2; } }
		public int icon { get { return m_icon; } }
		public int is_reddot { get { return m_is_reddot; } }
		public string Name { get { return m_Name; } }
		public int openid { get { return m_openid; } }
		public int Parameters { get { return m_Parameters; } }
		public int severcontrol { get { return m_severcontrol; } }
		public int showpane { get { return m_showpane; } }
		public int sort { get { return m_sort; } }
		public int special_open { get { return m_special_open; } }
		public int type { get { return m_type; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static MainMenu __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static MainMenu() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( MainMenu ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, MainMenu> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static MainMenu ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new MainMenu();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_cehuazijikan = __mask[ 0 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_cehuazijikan, 12 ) : __default.m_cehuazijikan;
				temp.m_effect = __mask[ 1 ] ? q.GetInt( DBCache.FID_effect, 6 ) : __default.m_effect;
				temp.m_effect2 = __mask[ 2 ] ? q.GetInt( DBCache.FID_effect2, 7 ) : __default.m_effect2;
				temp.m_icon = __mask[ 4 ] ? q.GetInt( DBCache.FID_icon, 4 ) : __default.m_icon;
				temp.m_is_reddot = __mask[ 5 ] ? q.GetInt( DBCache.FID_is_reddot, 9 ) : __default.m_is_reddot;
				temp.m_Name = __mask[ 6 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_Name, 4 ) : __default.m_Name;
				temp.m_openid = __mask[ 7 ] ? q.GetInt( DBCache.FID_openid, 6 ) : __default.m_openid;
				temp.m_Parameters = __mask[ 8 ] ? q.GetInt( DBCache.FID_Parameters, 10 ) : __default.m_Parameters;
				temp.m_severcontrol = __mask[ 9 ] ? q.GetInt( DBCache.FID_severcontrol, 12 ) : __default.m_severcontrol;
				temp.m_showpane = __mask[ 10 ] ? q.GetInt( DBCache.FID_showpane, 8 ) : __default.m_showpane;
				temp.m_sort = __mask[ 11 ] ? q.GetInt( DBCache.FID_sort, 4 ) : __default.m_sort;
				temp.m_special_open = __mask[ 12 ] ? q.GetInt( DBCache.FID_special_open, 12 ) : __default.m_special_open;
				temp.m_type = __mask[ 13 ] ? q.GetInt( DBCache.FID_type, 4 ) : __default.m_type;
				MainMenuEx.IsValid_guidesetting = __mask[ 3 ];
				if ( MainMenuEx.onLoadComplexField_guidesetting != null ) {
					MainMenuEx.onLoadComplexField_guidesetting( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static MainMenu Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			MainMenu ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x30da094f;
		#endregion
	}

	public partial class MainMenuEx {
		public delegate void LoadComplexField( MainMenu data, LuaDatabase.Query q );
		internal static bool IsValid_guidesetting = true;
		static LoadComplexField OnLoadComplexField_guidesetting = null;
		public static LoadComplexField onLoadComplexField_guidesetting {
			get {
				return OnLoadComplexField_guidesetting;
			}
		}
	}
}
//EOF
