//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class PlayerLvFunction {
		const string DBName = "player_lvfunction";
		#region members
		private int m_id = 0;
		private int m_durable_part_price = 0;
		private int m_level = 0;
		private int m_skill_lvup_gold = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, PlayerLvFunction> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, PlayerLvFunction>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int durable_part_price { get { return m_durable_part_price; } }
		public int level { get { return m_level; } }
		public int skill_lvup_gold { get { return m_skill_lvup_gold; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static PlayerLvFunction __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static PlayerLvFunction() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( PlayerLvFunction ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, PlayerLvFunction> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static PlayerLvFunction ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new PlayerLvFunction();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_durable_part_price = __mask[ 1 ] ? q.GetInt( DBCache.FID_durable_part_price, 18 ) : __default.m_durable_part_price;
				temp.m_level = __mask[ 3 ] ? q.GetInt( DBCache.FID_level, 5 ) : __default.m_level;
				temp.m_skill_lvup_gold = __mask[ 5 ] ? q.GetInt( DBCache.FID_skill_lvup_gold, 15 ) : __default.m_skill_lvup_gold;
				PlayerLvFunctionEx.IsValid_battle_ai_strong = __mask[ 0 ];
				PlayerLvFunctionEx.IsValid_equip_wash_gold = __mask[ 2 ];
				PlayerLvFunctionEx.IsValid_single_battle_re = __mask[ 4 ];
				PlayerLvFunctionEx.IsValid_skill_lvup_item = __mask[ 6 ];
				if ( PlayerLvFunctionEx.onLoadComplexField_battle_ai_strong != null ) {
					PlayerLvFunctionEx.onLoadComplexField_battle_ai_strong( temp, q );
				}
				if ( PlayerLvFunctionEx.onLoadComplexField_equip_wash_gold != null ) {
					PlayerLvFunctionEx.onLoadComplexField_equip_wash_gold( temp, q );
				}
				if ( PlayerLvFunctionEx.onLoadComplexField_single_battle_re != null ) {
					PlayerLvFunctionEx.onLoadComplexField_single_battle_re( temp, q );
				}
				if ( PlayerLvFunctionEx.onLoadComplexField_skill_lvup_item != null ) {
					PlayerLvFunctionEx.onLoadComplexField_skill_lvup_item( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static PlayerLvFunction Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			PlayerLvFunction ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x55c78260;
		#endregion
	}

	public partial class PlayerLvFunctionEx {
		public delegate void LoadComplexField( PlayerLvFunction data, LuaDatabase.Query q );
		internal static bool IsValid_battle_ai_strong = true;
		static LoadComplexField OnLoadComplexField_battle_ai_strong = null;
		public static LoadComplexField onLoadComplexField_battle_ai_strong {
			get {
				return OnLoadComplexField_battle_ai_strong;
			}
		}
		internal static bool IsValid_equip_wash_gold = true;
		static LoadComplexField OnLoadComplexField_equip_wash_gold = null;
		public static LoadComplexField onLoadComplexField_equip_wash_gold {
			get {
				return OnLoadComplexField_equip_wash_gold;
			}
		}
		internal static bool IsValid_single_battle_re = true;
		static LoadComplexField OnLoadComplexField_single_battle_re = null;
		public static LoadComplexField onLoadComplexField_single_battle_re {
			get {
				return OnLoadComplexField_single_battle_re;
			}
		}
		internal static bool IsValid_skill_lvup_item = true;
		static LoadComplexField OnLoadComplexField_skill_lvup_item = null;
		public static LoadComplexField onLoadComplexField_skill_lvup_item {
			get {
				return OnLoadComplexField_skill_lvup_item;
			}
		}
	}
}
//EOF
