//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class ShopFriendship {
		const string DBName = "shop_friendship";
		#region members
		private int m_id = 0;
		private int m_buy_level = 0;
		private int m_foreverLimit = 0;
		private string m_item_name = String.Empty;
		private int m_itemid = 0;
		private int m_maxchange = 0;
		private int m_Occupation = 0;
		private int m_openlv = 0;
		private int m_openType = 0;
		private int m_openValue = 0;
		private int m_ordernum = 0;
		private int m_payItem = 0;
		private int m_server_maxchange_day = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, ShopFriendship> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, ShopFriendship>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int buy_level { get { return m_buy_level; } }
		public int foreverLimit { get { return m_foreverLimit; } }
		public string item_name { get { return m_item_name; } }
		public int itemid { get { return m_itemid; } }
		public int maxchange { get { return m_maxchange; } }
		public int Occupation { get { return m_Occupation; } }
		public int openlv { get { return m_openlv; } }
		public int openType { get { return m_openType; } }
		public int openValue { get { return m_openValue; } }
		public int ordernum { get { return m_ordernum; } }
		public int payItem { get { return m_payItem; } }
		public int server_maxchange_day { get { return m_server_maxchange_day; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static ShopFriendship __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static ShopFriendship() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( ShopFriendship ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, ShopFriendship> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static ShopFriendship ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new ShopFriendship();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_buy_level = __mask[ 0 ] ? q.GetInt( DBCache.FID_buy_level, 9 ) : __default.m_buy_level;
				temp.m_foreverLimit = __mask[ 1 ] ? q.GetInt( DBCache.FID_foreverLimit, 12 ) : __default.m_foreverLimit;
				temp.m_item_name = __mask[ 2 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_item_name, 9 ) : __default.m_item_name;
				temp.m_itemid = __mask[ 3 ] ? q.GetInt( DBCache.FID_itemid, 6 ) : __default.m_itemid;
				temp.m_maxchange = __mask[ 4 ] ? q.GetInt( DBCache.FID_maxchange, 9 ) : __default.m_maxchange;
				temp.m_Occupation = __mask[ 5 ] ? q.GetInt( DBCache.FID_Occupation, 10 ) : __default.m_Occupation;
				temp.m_openlv = __mask[ 6 ] ? q.GetInt( DBCache.FID_openlv, 6 ) : __default.m_openlv;
				temp.m_openType = __mask[ 7 ] ? q.GetInt( DBCache.FID_openType, 8 ) : __default.m_openType;
				temp.m_openValue = __mask[ 8 ] ? q.GetInt( DBCache.FID_openValue, 9 ) : __default.m_openValue;
				temp.m_ordernum = __mask[ 9 ] ? q.GetInt( DBCache.FID_ordernum, 8 ) : __default.m_ordernum;
				temp.m_payItem = __mask[ 10 ] ? q.GetInt( DBCache.FID_payItem, 7 ) : __default.m_payItem;
				temp.m_server_maxchange_day = __mask[ 11 ] ? q.GetInt( DBCache.FID_server_maxchange_day, 20 ) : __default.m_server_maxchange_day;
				return temp;
			}
			return null;
		}

 		public static ShopFriendship Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			ShopFriendship ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x07b1555b;
		#endregion
	}
}
//EOF
