//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class ShopList {
		const string DBName = "shop_list";
		#region members
		private int m_id = 0;
		private int m_money_Type = 0;
		private int m_open_level = 0;
		private string m_open_time = String.Empty;
		private int m_reset_currency = 0;
		private int m_reset_currency_add = 0;
		private int m_reset_currency_max = 0;
		private int m_reset_currency_number = 0;
		private int m_reset_item = 0;
		private int m_reset_item_num = 0;
		private string m_shop_configure = String.Empty;
		private string m_shop_des = String.Empty;
		private string m_shop_name = String.Empty;
		private int m_sort = 0;
		private int m_window = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, ShopList> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, ShopList>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int money_Type { get { return m_money_Type; } }
		public int open_level { get { return m_open_level; } }
		public string open_time { get { return m_open_time; } }
		public int reset_currency { get { return m_reset_currency; } }
		public int reset_currency_add { get { return m_reset_currency_add; } }
		public int reset_currency_max { get { return m_reset_currency_max; } }
		public int reset_currency_number { get { return m_reset_currency_number; } }
		public int reset_item { get { return m_reset_item; } }
		public int reset_item_num { get { return m_reset_item_num; } }
		public string shop_configure { get { return m_shop_configure; } }
		public string shop_des { get { return m_shop_des; } }
		public string shop_name { get { return m_shop_name; } }
		public int sort { get { return m_sort; } }
		public int window { get { return m_window; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static ShopList __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static ShopList() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( ShopList ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, ShopList> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static ShopList ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new ShopList();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_money_Type = __mask[ 0 ] ? q.GetInt( DBCache.FID_money_Type, 10 ) : __default.m_money_Type;
				temp.m_open_level = __mask[ 1 ] ? q.GetInt( DBCache.FID_open_level, 10 ) : __default.m_open_level;
				temp.m_open_time = __mask[ 2 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_open_time, 9 ) : __default.m_open_time;
				temp.m_reset_currency = __mask[ 3 ] ? q.GetInt( DBCache.FID_reset_currency, 14 ) : __default.m_reset_currency;
				temp.m_reset_currency_add = __mask[ 4 ] ? q.GetInt( DBCache.FID_reset_currency_add, 18 ) : __default.m_reset_currency_add;
				temp.m_reset_currency_max = __mask[ 5 ] ? q.GetInt( DBCache.FID_reset_currency_max, 18 ) : __default.m_reset_currency_max;
				temp.m_reset_currency_number = __mask[ 6 ] ? q.GetInt( DBCache.FID_reset_currency_number, 21 ) : __default.m_reset_currency_number;
				temp.m_reset_item = __mask[ 7 ] ? q.GetInt( DBCache.FID_reset_item, 10 ) : __default.m_reset_item;
				temp.m_reset_item_num = __mask[ 8 ] ? q.GetInt( DBCache.FID_reset_item_num, 14 ) : __default.m_reset_item_num;
				temp.m_shop_configure = __mask[ 10 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_shop_configure, 14 ) : __default.m_shop_configure;
				temp.m_shop_des = __mask[ 11 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_shop_des, 8 ) : __default.m_shop_des;
				temp.m_shop_name = __mask[ 12 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_shop_name, 9 ) : __default.m_shop_name;
				temp.m_sort = __mask[ 13 ] ? q.GetInt( DBCache.FID_sort, 4 ) : __default.m_sort;
				temp.m_window = __mask[ 14 ] ? q.GetInt( DBCache.FID_window, 6 ) : __default.m_window;
				ShopListEx.IsValid_reset_time = __mask[ 9 ];
				if ( ShopListEx.onLoadComplexField_reset_time != null ) {
					ShopListEx.onLoadComplexField_reset_time( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static ShopList Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			ShopList ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x09715908;
		#endregion
	}

	public partial class ShopListEx {
		public delegate void LoadComplexField( ShopList data, LuaDatabase.Query q );
		internal static bool IsValid_reset_time = true;
		static LoadComplexField OnLoadComplexField_reset_time = null;
		public static LoadComplexField onLoadComplexField_reset_time {
			get {
				return OnLoadComplexField_reset_time;
			}
		}
	}
}
//EOF
