//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class ShowTwo {
		const string DBName = "show2";
		#region members
		private int m_id = 0;
		private string m_content = String.Empty;
		private int m_groupid = 0;
		private int m_head = 0;
		private int m_headtype = 0;
		private int m_modeloffset_ui = 0;
		private float m_modelscale_ui = 0;
		private int m_modelshuff_ui = 0;
		private int m_modelspin_ui = 0;
		private string m_name = String.Empty;
		private string m_show2_speech = String.Empty;
		private string m_side = String.Empty;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, ShowTwo> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, ShowTwo>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public string content { get { return m_content; } }
		public int groupid { get { return m_groupid; } }
		public int head { get { return m_head; } }
		public int headtype { get { return m_headtype; } }
		public int modeloffset_ui { get { return m_modeloffset_ui; } }
		public float modelscale_ui { get { return m_modelscale_ui; } }
		public int modelshuff_ui { get { return m_modelshuff_ui; } }
		public int modelspin_ui { get { return m_modelspin_ui; } }
		public string name { get { return m_name; } }
		public string show2_speech { get { return m_show2_speech; } }
		public string side { get { return m_side; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static ShowTwo __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static ShowTwo() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( ShowTwo ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, ShowTwo> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static ShowTwo ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new ShowTwo();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_content = __mask[ 0 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_content, 7 ) : __default.m_content;
				temp.m_groupid = __mask[ 1 ] ? q.GetInt( DBCache.FID_groupid, 7 ) : __default.m_groupid;
				temp.m_head = __mask[ 2 ] ? q.GetInt( DBCache.FID_head, 4 ) : __default.m_head;
				temp.m_headtype = __mask[ 3 ] ? q.GetInt( DBCache.FID_headtype, 8 ) : __default.m_headtype;
				temp.m_modeloffset_ui = __mask[ 4 ] ? q.GetInt( DBCache.FID_modeloffset_ui, 14 ) : __default.m_modeloffset_ui;
				temp.m_modelscale_ui = __mask[ 5 ] ? q.GetFloat( DBCache.FID_modelscale_ui, 13 ) : __default.m_modelscale_ui;
				temp.m_modelshuff_ui = __mask[ 6 ] ? q.GetInt( DBCache.FID_modelshuff_ui, 13 ) : __default.m_modelshuff_ui;
				temp.m_modelspin_ui = __mask[ 7 ] ? q.GetInt( DBCache.FID_modelspin_ui, 12 ) : __default.m_modelspin_ui;
				temp.m_name = __mask[ 8 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_name, 4 ) : __default.m_name;
				temp.m_show2_speech = __mask[ 9 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_show2_speech, 12 ) : __default.m_show2_speech;
				temp.m_side = __mask[ 10 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_side, 4 ) : __default.m_side;
				return temp;
			}
			return null;
		}

 		public static ShowTwo Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			ShowTwo ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x017fde21;
		#endregion
	}
}
//EOF
