//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class SngleTower {
		const string DBName = "single_tower";
		#region members
		private int m_id = 0;
		private int m_chall_time = 0;
		private int m_interval = 0;
		private int m_level_limit = 0;
		private int m_refresh_monster = 0;
		private int m_type = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, SngleTower> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, SngleTower>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int chall_time { get { return m_chall_time; } }
		public int interval { get { return m_interval; } }
		public int level_limit { get { return m_level_limit; } }
		public int refresh_monster { get { return m_refresh_monster; } }
		public int type { get { return m_type; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static SngleTower __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static SngleTower() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( SngleTower ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, SngleTower> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static SngleTower ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new SngleTower();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_chall_time = __mask[ 0 ] ? q.GetInt( DBCache.FID_chall_time, 10 ) : __default.m_chall_time;
				temp.m_interval = __mask[ 4 ] ? q.GetInt( DBCache.FID_interval, 8 ) : __default.m_interval;
				temp.m_level_limit = __mask[ 5 ] ? q.GetInt( DBCache.FID_level_limit, 11 ) : __default.m_level_limit;
				temp.m_refresh_monster = __mask[ 7 ] ? q.GetInt( DBCache.FID_refresh_monster, 15 ) : __default.m_refresh_monster;
				temp.m_type = __mask[ 10 ] ? q.GetInt( DBCache.FID_type, 4 ) : __default.m_type;
				SngleTowerEx.IsValid_floor_firstrew = __mask[ 1 ];
				SngleTowerEx.IsValid_floor_thistar_rew = __mask[ 2 ];
				SngleTowerEx.IsValid_floor_twostar_rew = __mask[ 3 ];
				SngleTowerEx.IsValid_Monster = __mask[ 6 ];
				SngleTowerEx.IsValid_special_show = __mask[ 8 ];
				SngleTowerEx.IsValid_star_condition = __mask[ 9 ];
				if ( SngleTowerEx.onLoadComplexField_floor_firstrew != null ) {
					SngleTowerEx.onLoadComplexField_floor_firstrew( temp, q );
				}
				if ( SngleTowerEx.onLoadComplexField_floor_thistar_rew != null ) {
					SngleTowerEx.onLoadComplexField_floor_thistar_rew( temp, q );
				}
				if ( SngleTowerEx.onLoadComplexField_floor_twostar_rew != null ) {
					SngleTowerEx.onLoadComplexField_floor_twostar_rew( temp, q );
				}
				if ( SngleTowerEx.onLoadComplexField_Monster != null ) {
					SngleTowerEx.onLoadComplexField_Monster( temp, q );
				}
				if ( SngleTowerEx.onLoadComplexField_special_show != null ) {
					SngleTowerEx.onLoadComplexField_special_show( temp, q );
				}
				if ( SngleTowerEx.onLoadComplexField_star_condition != null ) {
					SngleTowerEx.onLoadComplexField_star_condition( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static SngleTower Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			SngleTower ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x78b59db4;
		#endregion
	}

	public partial class SngleTowerEx {
		public delegate void LoadComplexField( SngleTower data, LuaDatabase.Query q );
		internal static bool IsValid_floor_firstrew = true;
		static LoadComplexField OnLoadComplexField_floor_firstrew = null;
		public static LoadComplexField onLoadComplexField_floor_firstrew {
			get {
				return OnLoadComplexField_floor_firstrew;
			}
		}
		internal static bool IsValid_floor_thistar_rew = true;
		static LoadComplexField OnLoadComplexField_floor_thistar_rew = null;
		public static LoadComplexField onLoadComplexField_floor_thistar_rew {
			get {
				return OnLoadComplexField_floor_thistar_rew;
			}
		}
		internal static bool IsValid_floor_twostar_rew = true;
		static LoadComplexField OnLoadComplexField_floor_twostar_rew = null;
		public static LoadComplexField onLoadComplexField_floor_twostar_rew {
			get {
				return OnLoadComplexField_floor_twostar_rew;
			}
		}
		internal static bool IsValid_Monster = true;
		static LoadComplexField OnLoadComplexField_Monster = null;
		public static LoadComplexField onLoadComplexField_Monster {
			get {
				return OnLoadComplexField_Monster;
			}
		}
		internal static bool IsValid_special_show = true;
		static LoadComplexField OnLoadComplexField_special_show = null;
		public static LoadComplexField onLoadComplexField_special_show {
			get {
				return OnLoadComplexField_special_show;
			}
		}
		internal static bool IsValid_star_condition = true;
		static LoadComplexField OnLoadComplexField_star_condition = null;
		public static LoadComplexField onLoadComplexField_star_condition {
			get {
				return OnLoadComplexField_star_condition;
			}
		}
	}
}
//EOF
