//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class TmeReward {
		const string DBName = "time_reward";
		#region members
		private int m_id = 0;
		private int m_get_level = 0;
		private int m_get_loginday = 0;
		private int m_get_time = 0;
		private int m_gettype = 0;
		private string m_model_name_c1 = String.Empty;
		private string m_model_name_c2 = String.Empty;
		private string m_model_name_c3 = String.Empty;
		private string m_model_name_c4 = String.Empty;
		private string m_name = String.Empty;
		private int m_nameicon = 0;
		private int m_opensoul = 0;
		private string m_type1 = String.Empty;
		private string m_type2 = String.Empty;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, TmeReward> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, TmeReward>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int get_level { get { return m_get_level; } }
		public int get_loginday { get { return m_get_loginday; } }
		public int get_time { get { return m_get_time; } }
		public int gettype { get { return m_gettype; } }
		public string model_name_c1 { get { return m_model_name_c1; } }
		public string model_name_c2 { get { return m_model_name_c2; } }
		public string model_name_c3 { get { return m_model_name_c3; } }
		public string model_name_c4 { get { return m_model_name_c4; } }
		public string name { get { return m_name; } }
		public int nameicon { get { return m_nameicon; } }
		public int opensoul { get { return m_opensoul; } }
		public string type1 { get { return m_type1; } }
		public string type2 { get { return m_type2; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static TmeReward __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static TmeReward() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( TmeReward ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, TmeReward> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static TmeReward ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new TmeReward();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_get_level = __mask[ 4 ] ? q.GetInt( DBCache.FID_get_level, 9 ) : __default.m_get_level;
				temp.m_get_loginday = __mask[ 5 ] ? q.GetInt( DBCache.FID_get_loginday, 12 ) : __default.m_get_loginday;
				temp.m_get_time = __mask[ 6 ] ? q.GetInt( DBCache.FID_get_time, 8 ) : __default.m_get_time;
				temp.m_gettype = __mask[ 7 ] ? q.GetInt( DBCache.FID_gettype, 7 ) : __default.m_gettype;
				temp.m_model_name_c1 = __mask[ 9 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_model_name_c1, 13 ) : __default.m_model_name_c1;
				temp.m_model_name_c2 = __mask[ 10 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_model_name_c2, 13 ) : __default.m_model_name_c2;
				temp.m_model_name_c3 = __mask[ 11 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_model_name_c3, 13 ) : __default.m_model_name_c3;
				temp.m_model_name_c4 = __mask[ 12 ] ? Dataset.DecodeToDatabaseString( q, DBCache.FID_model_name_c4, 13 ) : __default.m_model_name_c4;
				temp.m_name = __mask[ 15 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_name, 4 ) : __default.m_name;
				temp.m_nameicon = __mask[ 16 ] ? q.GetInt( DBCache.FID_nameicon, 8 ) : __default.m_nameicon;
				temp.m_opensoul = __mask[ 17 ] ? q.GetInt( DBCache.FID_opensoul, 8 ) : __default.m_opensoul;
				temp.m_type1 = __mask[ 18 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_type1, 5 ) : __default.m_type1;
				temp.m_type2 = __mask[ 19 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_type2, 5 ) : __default.m_type2;
				TmeRewardEx.IsValid_c1 = __mask[ 0 ];
				TmeRewardEx.IsValid_c2 = __mask[ 1 ];
				TmeRewardEx.IsValid_c3 = __mask[ 2 ];
				TmeRewardEx.IsValid_c4 = __mask[ 3 ];
				TmeRewardEx.IsValid_model_hight = __mask[ 8 ];
				TmeRewardEx.IsValid_model_s = __mask[ 13 ];
				TmeRewardEx.IsValid_model_zoom = __mask[ 14 ];
				if ( TmeRewardEx.onLoadComplexField_c1 != null ) {
					TmeRewardEx.onLoadComplexField_c1( temp, q );
				}
				if ( TmeRewardEx.onLoadComplexField_c2 != null ) {
					TmeRewardEx.onLoadComplexField_c2( temp, q );
				}
				if ( TmeRewardEx.onLoadComplexField_c3 != null ) {
					TmeRewardEx.onLoadComplexField_c3( temp, q );
				}
				if ( TmeRewardEx.onLoadComplexField_c4 != null ) {
					TmeRewardEx.onLoadComplexField_c4( temp, q );
				}
				if ( TmeRewardEx.onLoadComplexField_model_hight != null ) {
					TmeRewardEx.onLoadComplexField_model_hight( temp, q );
				}
				if ( TmeRewardEx.onLoadComplexField_model_s != null ) {
					TmeRewardEx.onLoadComplexField_model_s( temp, q );
				}
				if ( TmeRewardEx.onLoadComplexField_model_zoom != null ) {
					TmeRewardEx.onLoadComplexField_model_zoom( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static TmeReward Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			TmeReward ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x3ff393ac;
		#endregion
	}

	public partial class TmeRewardEx {
		public delegate void LoadComplexField( TmeReward data, LuaDatabase.Query q );
		internal static bool IsValid_c1 = true;
		static LoadComplexField OnLoadComplexField_c1 = null;
		public static LoadComplexField onLoadComplexField_c1 {
			get {
				return OnLoadComplexField_c1;
			}
		}
		internal static bool IsValid_c2 = true;
		static LoadComplexField OnLoadComplexField_c2 = null;
		public static LoadComplexField onLoadComplexField_c2 {
			get {
				return OnLoadComplexField_c2;
			}
		}
		internal static bool IsValid_c3 = true;
		static LoadComplexField OnLoadComplexField_c3 = null;
		public static LoadComplexField onLoadComplexField_c3 {
			get {
				return OnLoadComplexField_c3;
			}
		}
		internal static bool IsValid_c4 = true;
		static LoadComplexField OnLoadComplexField_c4 = null;
		public static LoadComplexField onLoadComplexField_c4 {
			get {
				return OnLoadComplexField_c4;
			}
		}
		internal static bool IsValid_model_hight = true;
		static LoadComplexField OnLoadComplexField_model_hight = null;
		public static LoadComplexField onLoadComplexField_model_hight {
			get {
				return OnLoadComplexField_model_hight;
			}
		}
		internal static bool IsValid_model_s = true;
		static LoadComplexField OnLoadComplexField_model_s = null;
		public static LoadComplexField onLoadComplexField_model_s {
			get {
				return OnLoadComplexField_model_s;
			}
		}
		internal static bool IsValid_model_zoom = true;
		static LoadComplexField OnLoadComplexField_model_zoom = null;
		public static LoadComplexField onLoadComplexField_model_zoom {
			get {
				return OnLoadComplexField_model_zoom;
			}
		}
	}
}
//EOF
