//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class Underground {
		const string DBName = "Underground";
		#region members
		private int m_id = 0;
		private int m_boss_refresh = 0;
		private string m_des = String.Empty;
		private string m_des_pk = String.Empty;
		private int m_guild_num = 0;
		private int m_jjc_rank = 0;
		private int m_map_id = 0;
		private int m_open_time = 0;
		private int m_pic1 = 0;
		private int m_pic2 = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, Underground> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, Underground>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int boss_refresh { get { return m_boss_refresh; } }
		public string des { get { return m_des; } }
		public string des_pk { get { return m_des_pk; } }
		public int guild_num { get { return m_guild_num; } }
		public int jjc_rank { get { return m_jjc_rank; } }
		public int map_id { get { return m_map_id; } }
		public int open_time { get { return m_open_time; } }
		public int pic1 { get { return m_pic1; } }
		public int pic2 { get { return m_pic2; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static Underground __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static Underground() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( Underground ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, Underground> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static Underground ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new Underground();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_boss_refresh = __mask[ 0 ] ? q.GetInt( DBCache.FID_boss_refresh, 12 ) : __default.m_boss_refresh;
				temp.m_des = __mask[ 1 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_des, 3 ) : __default.m_des;
				temp.m_des_pk = __mask[ 2 ] ? Dataset.DecodeToLocalizedString( q, DBCache.FID_des_pk, 6 ) : __default.m_des_pk;
				temp.m_guild_num = __mask[ 3 ] ? q.GetInt( DBCache.FID_guild_num, 9 ) : __default.m_guild_num;
				temp.m_jjc_rank = __mask[ 4 ] ? q.GetInt( DBCache.FID_jjc_rank, 8 ) : __default.m_jjc_rank;
				temp.m_map_id = __mask[ 5 ] ? q.GetInt( DBCache.FID_map_id, 6 ) : __default.m_map_id;
				temp.m_open_time = __mask[ 6 ] ? q.GetInt( DBCache.FID_open_time, 9 ) : __default.m_open_time;
				temp.m_pic1 = __mask[ 7 ] ? q.GetInt( DBCache.FID_pic1, 4 ) : __default.m_pic1;
				temp.m_pic2 = __mask[ 8 ] ? q.GetInt( DBCache.FID_pic2, 4 ) : __default.m_pic2;
				return temp;
			}
			return null;
		}

 		public static Underground Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			Underground ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x4d993999;
		#endregion
	}
}
//EOF
