//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
#endif

namespace Database {
	public partial class VipDescribe {
		const string DBName = "vip_describe";
		#region members
		private int m_id = 0;
		private string m_describe = String.Empty;
		#endregion
		#region caches
		private static List<int> m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, VipDescribe> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, VipDescribe>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public string describe { get { return m_describe; } }
		#endregion
		#region method
		static VipDescribe() {
			if ( LuaDatabase.sharedInstance.Load( DBName ) ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( VipDescribe ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, VipDescribe> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return LuaDatabase.sharedInstance.Load( DBName );
		}

		public static bool Load() {
			return LuaDatabase.sharedInstance.Load( DBName );
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ClearCache();
			return ret;
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				LuaDatabase.LuaTable_iForEach( L,
					( _L, id ) => {
						using ( var q = db.CreateQuery( -1, DBName ) ) {
							var value = ReadOne( q, id );
							if ( value != null ) {
								m_idCache.Add( id, value );
							}
						}
					}
				);
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static List<int> GetKeys( bool sort = false, Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, sort, pred );
			}
			var ids = m_ids;
			if ( sort ) {
				int count = m_ids.Count;
				ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					ids.Add( m_ids[i] );
				}
				if ( pred == null ) {
					ids.Sort();
				} else {
					ids.Sort( pred );
				}
			}
			return ids;;
		}

		static VipDescribe ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new VipDescribe();
				temp.m_id = id;
				temp.m_describe = Dataset.DecodeToLocalizedString( q, "describe" );
				return temp;
			}
			return null;
		}

 		public static VipDescribe Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			VipDescribe ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		#endregion
	}
}
//EOF
