//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY LUA DATABASE TOOL.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

using System;
using System.Collections.Generic;
using Common;
#if USE_NATIVE_LUA
using NLuaState = NativeLua.NLuaState;
using LuaType = NativeLua.LuaDLL;
using LuaTinker = NativeLua.LuaTinker;
using LuaDatabase = NativeLua.LuaDatabase;
using LuaTableHandle = System.Int64;
using LuaStateHandle = System.IntPtr;
#else
using NLuaState = UniLua.ILuaState;
using LuaType = UniLua.LuaType;
using LuaTinker = UniLuax.LuaTinker;
using LuaDatabase = UniLuax.LuaDatabase;
using LuaTableHandle = System.Object;
using LuaStateHandle = UniLua.ILuaState;
#endif

namespace Database {
	public partial class WorldbossSetting {
		const string DBName = "worldboss_setting";
		#region members
		private int m_id = 0;
		private int m_boss_x = 0;
		private int m_boss_y = 0;
		private int m_bossid = 0;
		private int m_mapid = 0;
		#endregion
		#region caches
		private static IKeys m_ids = null;
		private static Common.Collections.Generic.Lit.Dictionary<int, WorldbossSetting> m_idCache = new Common.Collections.Generic.Lit.Dictionary<int, WorldbossSetting>();
		#endregion
		#region properties
		public int id { get { return m_id; } }
		public int boss_x { get { return m_boss_x; } }
		public int boss_y { get { return m_boss_y; } }
		public int bossid { get { return m_bossid; } }
		public int mapid { get { return m_mapid; } }
		#endregion
		#region method
		static LuaTableHandle __this = default( LuaTableHandle );
		static WorldbossSetting __default = null;
		static int __hash = 0;
		static bool __masked = false;

		static WorldbossSetting() {
			LuaDatabase.datasetUnloadEvent += OnUnload;
			if ( Load() ) {
				DBLoadedItems.MarkAutoLoaded( DBName, typeof( WorldbossSetting ) );
			}
		}

		public static String DbName {
			get { return DBName; }
		}

		public static Common.Collections.Generic.Lit.Dictionary<int, WorldbossSetting> idCacheData {
			get { return m_idCache; }
		}

		public static void Touch() {
		}

		public static bool EnsureLoaded() {
			return Load();
		}

		static void ReadDefault() {
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				if ( L.IsTable( -1 ) ) {
					L.GetMetaTable( -1 );
					if ( L.IsTable( -1 ) ) {
						__this = ( LuaTableHandle )L.ToObject( -1 );
						var table = new LuaTinker.Table( L, -1 );
						var subTable = table.GetSubTable( "__default" );
						__masked = table.Get<bool>( "__masked", false );
						__hash = table.Get<int>( "__hash", 0 );
						if ( subTable != LuaTinker.Table.Empty && __hash == VersionHash ) {
							using ( var q = db.CreateQuery( subTable.index ) ) {
								__default = ReadOne( q, default( int ) );
							}
						} else {
							if ( __hash != 0 ) {
								ULogFile.sharedInstance.LogError( "Database {0} version mismatch, reader = 0x{1:x8}, data = 0x{2:x8}, masked = {3} ", DBName, VersionHash, __hash, __masked );
							}
							__masked = false;
						}
					}
				}
			} finally {
				db.SetLuaTop( top );
			}
		}

		public static bool Load() {
			bool alreadyLoaded;
			var r = LuaDatabase.sharedInstance.Load( DBName, out alreadyLoaded );
			if ( r && !alreadyLoaded ) {
				ReadDefault();
			}
			return r;
		}

		public static bool IsLoaded() {
			return LuaDatabase.sharedInstance.IsLoaded( DBName );
		}

		public static bool Unload() {
			return LuaDatabase.sharedInstance.Unload( DBName );
		}

		public static bool Reload() {
			bool ret = LuaDatabase.sharedInstance.Reload( DBName );
			ReadDefault();
			ClearCache();
			return ret;
		}

		static void OnUnload( LuaStateHandle L, LuaTableHandle tablePtr, String name ) {
			if ( name == DBName && tablePtr == __this ) {
				__this = default( LuaTableHandle );
				__default = null;
				__hash = 0;
				__masked = false;
			}
		}

		public static int CacheAll() {
			ClearCache();
			var db = LuaDatabase.sharedInstance;
			var L = db.GetLuaState();
			var top = db.GetLuaTop();
			try {
				db.PushDataset( DBName );
				using ( var gbuff = Common.GlobalBuffer<int>.Get() ) {
					LuaDatabase.LuaTable_iForEach( L,
						( _L, id ) => {
							using ( var q = db.CreateQuery( -1, DBName ) ) {
								var value = ReadOne( q, id );
								if ( value != null ) {
									m_idCache.Add( id, value );
									gbuff.Add( id );
								}
							}
						}
					);
					gbuff.Sort();
					m_ids = new IKeys( gbuff.ToList() );
				};
			} finally {
				db.SetLuaTop( top );
			}
			return m_idCache.Count;
		}

		public static void ClearCache() {
			m_idCache.Clear();
			m_ids = null;
		}

		public static int Sweep( bool force = false ) {
			return 0;
		}

		public static IKeys GetKeys( Comparison<int> pred = null ) {
			if ( m_ids == null ) {
				m_ids = new IKeys( LuaDatabase.sharedInstance.GetDatasetIKeys( DBName, true, pred ) );
			}
			var ids = m_ids;
			if ( pred != null ) {
				int count = m_ids.Count;
				var _ids = new List<int>( count );
				for ( int i = 0; i < count; ++i ) {
					_ids.Add( m_ids[i] );
				}
				_ids.Sort( pred );
				ids = new IKeys( _ids );
			}
			return ids;
		}

		static WorldbossSetting ReadOne( LuaDatabase.Query q, int id ) {
			if ( q.IsTable() ) {
				var temp = new WorldbossSetting();
				var __mask = DBCache.LoadCurrentFieldMask( q, __masked );
				temp.m_id = id;
				temp.m_boss_x = __mask[ 0 ] ? q.GetInt( DBCache.FID_boss_x, 6 ) : __default.m_boss_x;
				temp.m_boss_y = __mask[ 1 ] ? q.GetInt( DBCache.FID_boss_y, 6 ) : __default.m_boss_y;
				temp.m_bossid = __mask[ 2 ] ? q.GetInt( DBCache.FID_bossid, 6 ) : __default.m_bossid;
				temp.m_mapid = __mask[ 3 ] ? q.GetInt( DBCache.FID_mapid, 5 ) : __default.m_mapid;
				WorldbossSettingEx.IsValid_PlayerNo1 = __mask[ 4 ];
				WorldbossSettingEx.IsValid_PlayerNo2 = __mask[ 5 ];
				WorldbossSettingEx.IsValid_PlayerNo3 = __mask[ 6 ];
				WorldbossSettingEx.IsValid_PlayerNo4 = __mask[ 7 ];
				WorldbossSettingEx.IsValid_PlayerNo5 = __mask[ 8 ];
				WorldbossSettingEx.IsValid_PlayerNo6 = __mask[ 9 ];
				WorldbossSettingEx.IsValid_PlayerNo7 = __mask[ 10 ];
				WorldbossSettingEx.IsValid_PlayerNo8 = __mask[ 11 ];
				WorldbossSettingEx.IsValid_RewardAll = __mask[ 12 ];
				WorldbossSettingEx.IsValid_Rewarditem1 = __mask[ 13 ];
				WorldbossSettingEx.IsValid_Rewarditem2 = __mask[ 14 ];
				WorldbossSettingEx.IsValid_Rewarditem3 = __mask[ 15 ];
				WorldbossSettingEx.IsValid_Rewarditem4 = __mask[ 16 ];
				WorldbossSettingEx.IsValid_Rewarditem5 = __mask[ 17 ];
				WorldbossSettingEx.IsValid_Rewarditem6 = __mask[ 18 ];
				WorldbossSettingEx.IsValid_Rewarditem7 = __mask[ 19 ];
				WorldbossSettingEx.IsValid_Rewarditem8 = __mask[ 20 ];
				if ( WorldbossSettingEx.onLoadComplexField_PlayerNo1 != null ) {
					WorldbossSettingEx.onLoadComplexField_PlayerNo1( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_PlayerNo2 != null ) {
					WorldbossSettingEx.onLoadComplexField_PlayerNo2( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_PlayerNo3 != null ) {
					WorldbossSettingEx.onLoadComplexField_PlayerNo3( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_PlayerNo4 != null ) {
					WorldbossSettingEx.onLoadComplexField_PlayerNo4( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_PlayerNo5 != null ) {
					WorldbossSettingEx.onLoadComplexField_PlayerNo5( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_PlayerNo6 != null ) {
					WorldbossSettingEx.onLoadComplexField_PlayerNo6( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_PlayerNo7 != null ) {
					WorldbossSettingEx.onLoadComplexField_PlayerNo7( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_PlayerNo8 != null ) {
					WorldbossSettingEx.onLoadComplexField_PlayerNo8( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_RewardAll != null ) {
					WorldbossSettingEx.onLoadComplexField_RewardAll( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_Rewarditem1 != null ) {
					WorldbossSettingEx.onLoadComplexField_Rewarditem1( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_Rewarditem2 != null ) {
					WorldbossSettingEx.onLoadComplexField_Rewarditem2( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_Rewarditem3 != null ) {
					WorldbossSettingEx.onLoadComplexField_Rewarditem3( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_Rewarditem4 != null ) {
					WorldbossSettingEx.onLoadComplexField_Rewarditem4( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_Rewarditem5 != null ) {
					WorldbossSettingEx.onLoadComplexField_Rewarditem5( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_Rewarditem6 != null ) {
					WorldbossSettingEx.onLoadComplexField_Rewarditem6( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_Rewarditem7 != null ) {
					WorldbossSettingEx.onLoadComplexField_Rewarditem7( temp, q );
				}
				if ( WorldbossSettingEx.onLoadComplexField_Rewarditem8 != null ) {
					WorldbossSettingEx.onLoadComplexField_Rewarditem8( temp, q );
				}
				return temp;
			}
			return null;
		}

 		public static WorldbossSetting Get( int id ) {
			if ( id == 0 ) {
				return null;
			}
			WorldbossSetting ret = null;
			if ( m_idCache.TryGetValue( id, out ret ) ) {
				return ret;
			}
			var db = LuaDatabase.sharedInstance;
			int tableIndex = db.PushDatasetValue( DBName, id );
			var L = db.GetLuaState();
			if ( L.IsTable( tableIndex ) == false ) {
			    L.Remove( tableIndex );
			    Common.UDebug.LogError( "{0}[{1}] is nil", DBName, id );
			    return null;
			}
			using ( var q = db.CreateQuery( tableIndex, DBName ) ) {
				var temp = ReadOne( q, id );
				if ( temp != null ) {
					m_idCache.Add( id, temp );
					return temp;
				}
			}
			return null;
		}

		const int VersionHash = 0x099b596d;
		#endregion
	}

	public partial class WorldbossSettingEx {
		public delegate void LoadComplexField( WorldbossSetting data, LuaDatabase.Query q );
		internal static bool IsValid_PlayerNo1 = true;
		static LoadComplexField OnLoadComplexField_PlayerNo1 = null;
		public static LoadComplexField onLoadComplexField_PlayerNo1 {
			get {
				return OnLoadComplexField_PlayerNo1;
			}
		}
		internal static bool IsValid_PlayerNo2 = true;
		static LoadComplexField OnLoadComplexField_PlayerNo2 = null;
		public static LoadComplexField onLoadComplexField_PlayerNo2 {
			get {
				return OnLoadComplexField_PlayerNo2;
			}
		}
		internal static bool IsValid_PlayerNo3 = true;
		static LoadComplexField OnLoadComplexField_PlayerNo3 = null;
		public static LoadComplexField onLoadComplexField_PlayerNo3 {
			get {
				return OnLoadComplexField_PlayerNo3;
			}
		}
		internal static bool IsValid_PlayerNo4 = true;
		static LoadComplexField OnLoadComplexField_PlayerNo4 = null;
		public static LoadComplexField onLoadComplexField_PlayerNo4 {
			get {
				return OnLoadComplexField_PlayerNo4;
			}
		}
		internal static bool IsValid_PlayerNo5 = true;
		static LoadComplexField OnLoadComplexField_PlayerNo5 = null;
		public static LoadComplexField onLoadComplexField_PlayerNo5 {
			get {
				return OnLoadComplexField_PlayerNo5;
			}
		}
		internal static bool IsValid_PlayerNo6 = true;
		static LoadComplexField OnLoadComplexField_PlayerNo6 = null;
		public static LoadComplexField onLoadComplexField_PlayerNo6 {
			get {
				return OnLoadComplexField_PlayerNo6;
			}
		}
		internal static bool IsValid_PlayerNo7 = true;
		static LoadComplexField OnLoadComplexField_PlayerNo7 = null;
		public static LoadComplexField onLoadComplexField_PlayerNo7 {
			get {
				return OnLoadComplexField_PlayerNo7;
			}
		}
		internal static bool IsValid_PlayerNo8 = true;
		static LoadComplexField OnLoadComplexField_PlayerNo8 = null;
		public static LoadComplexField onLoadComplexField_PlayerNo8 {
			get {
				return OnLoadComplexField_PlayerNo8;
			}
		}
		internal static bool IsValid_RewardAll = true;
		static LoadComplexField OnLoadComplexField_RewardAll = null;
		public static LoadComplexField onLoadComplexField_RewardAll {
			get {
				return OnLoadComplexField_RewardAll;
			}
		}
		internal static bool IsValid_Rewarditem1 = true;
		static LoadComplexField OnLoadComplexField_Rewarditem1 = null;
		public static LoadComplexField onLoadComplexField_Rewarditem1 {
			get {
				return OnLoadComplexField_Rewarditem1;
			}
		}
		internal static bool IsValid_Rewarditem2 = true;
		static LoadComplexField OnLoadComplexField_Rewarditem2 = null;
		public static LoadComplexField onLoadComplexField_Rewarditem2 {
			get {
				return OnLoadComplexField_Rewarditem2;
			}
		}
		internal static bool IsValid_Rewarditem3 = true;
		static LoadComplexField OnLoadComplexField_Rewarditem3 = null;
		public static LoadComplexField onLoadComplexField_Rewarditem3 {
			get {
				return OnLoadComplexField_Rewarditem3;
			}
		}
		internal static bool IsValid_Rewarditem4 = true;
		static LoadComplexField OnLoadComplexField_Rewarditem4 = null;
		public static LoadComplexField onLoadComplexField_Rewarditem4 {
			get {
				return OnLoadComplexField_Rewarditem4;
			}
		}
		internal static bool IsValid_Rewarditem5 = true;
		static LoadComplexField OnLoadComplexField_Rewarditem5 = null;
		public static LoadComplexField onLoadComplexField_Rewarditem5 {
			get {
				return OnLoadComplexField_Rewarditem5;
			}
		}
		internal static bool IsValid_Rewarditem6 = true;
		static LoadComplexField OnLoadComplexField_Rewarditem6 = null;
		public static LoadComplexField onLoadComplexField_Rewarditem6 {
			get {
				return OnLoadComplexField_Rewarditem6;
			}
		}
		internal static bool IsValid_Rewarditem7 = true;
		static LoadComplexField OnLoadComplexField_Rewarditem7 = null;
		public static LoadComplexField onLoadComplexField_Rewarditem7 {
			get {
				return OnLoadComplexField_Rewarditem7;
			}
		}
		internal static bool IsValid_Rewarditem8 = true;
		static LoadComplexField OnLoadComplexField_Rewarditem8 = null;
		public static LoadComplexField onLoadComplexField_Rewarditem8 {
			get {
				return OnLoadComplexField_Rewarditem8;
			}
		}
	}
}
//EOF
